# Generated by Django 2.2.27 on 2025-09-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_task_console_link'),
        ('app', '0002_tapis_oauth2_models'),
    ]

    operations = [
    ]
