# Generated by Django 2.2.27 on 2025-09-10 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0045_merge_20250910_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapisUserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_discover_on_login', models.BooleanField(default=True, help_text='Automatically discover and create projects from flight data on Tapis login')),
                ('max_projects_per_discovery', models.IntegerField(default=50, help_text='Maximum number of projects to create in a single discovery session')),
                ('discovery_cooldown_hours', models.IntegerField(default=24, help_text='Hours to wait between automatic discovery runs for the same user')),
                ('notify_on_discovery_complete', models.BooleanField(default=True, help_text='Send notification when flight discovery creates new projects')),
                ('notify_on_discovery_errors', models.BooleanField(default=True, help_text='Send notification when flight discovery encounters errors')),
                ('preferred_systems', models.TextField(blank=True, help_text='Comma-separated list of preferred ptdatax.project.* systems to scan (empty = all systems)')),
                ('last_auto_discovery', models.DateTimeField(blank=True, help_text='Timestamp of last automatic discovery run', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tapis User Preferences',
                'verbose_name_plural': 'Tapis User Preferences',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tapisoauth2token',
            name='unique_user_client_token',
        ),
        migrations.AlterField(
            model_name='tapisoauth2state',
            name='additional_data',
            field=models.TextField(blank=True, default='{}', help_text='Additional data to store during OAuth flow (JSON string)'),
        ),
        migrations.AlterUniqueTogether(
            name='tapisoauth2token',
            unique_together={('user', 'client')},
        ),
        migrations.AddField(
            model_name='tapisuserpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tapis_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
