name: webodm-checkpoint-local

services:
  db:
    image: opendronemap/webodm_db
    volumes:
      - ./.local-dev/db:/var/lib/postgresql/data
    restart: unless-stopped

  broker:
    image: redis:7.0.10
    restart: unless-stopped

  node-odm:
    image: opendronemap/nodeodm
    ports:
      - "${LOCAL_DEV_BIND_IP:-127.0.0.1}:${LOCAL_DEV_NODEODM_PORT:-13001}:3000"
    volumes:
      - ./.local-dev/nodeodm-data:/var/www/data
    restart: unless-stopped

  clusterodm:
    image: clusterodm:ls6-checkpoint-local
    build:
      context: ../../ClusterODM
      dockerfile: Dockerfile.local-dev
    command:
      - --port
      - "3000"
      - --admin-cli-port
      - "0"
      - --admin-web-port
      - "10000"
      - --admin-web-use-tapis-jwt=false
      - --log-level
      - debug
      - --public-address
      - http://clusterodm:3000
    depends_on:
      - node-odm
    ports:
      - "${LOCAL_DEV_BIND_IP:-127.0.0.1}:${LOCAL_DEV_CLUSTERODM_PORT:-14000}:3000"
      - "${LOCAL_DEV_BIND_IP:-127.0.0.1}:${LOCAL_DEV_CLUSTERODM_ADMIN_PORT:-11000}:10000"
    volumes:
      - ./.local-dev/clusterodm-data:/var/www/data
    restart: unless-stopped

  webapp:
    image: webodm:ls6-checkpoint-local
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ./webodm.env
    entrypoint: /bin/bash -c "service cron start && chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/scripts/entrypoint-tapis.sh /webodm/start.sh\""
    depends_on:
      - db
      - broker
      - worker
      - clusterodm
    ports:
      - "${LOCAL_DEV_BIND_IP:-127.0.0.1}:${LOCAL_DEV_WEBODM_PORT:-18000}:8000"
    volumes:
      - ./.local-dev/media:/webodm/app/media
    restart: unless-stopped

  worker:
    image: webodm:ls6-checkpoint-local
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ./webodm.env
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/scripts/entrypoint-tapis.sh /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    depends_on:
      - db
      - broker
      - clusterodm
    volumes:
      - ./.local-dev/media:/webodm/app/media
    restart: unless-stopped
