"""
Server-to-server client for Label Studio's own REST API.

Decision 32 (docs/design/2026-07-22-geospatial-embeddings-classification.md):
Label Studio's REST API only accepts Label Studio's OWN Personal Access Token
(`Authorization: Bearer <token>`) -- it does NOT accept a Tapis JWT. The
human deep-link SSO login (handled entirely by the separate
`label-studio-tapis-auth` repo's `TapisOAuth2Backend`) is a completely
different code path from the server-to-server calls this module makes:
project create, task import, and webhook registration all run with no human
in the loop. Every method here authenticates with
`settings.WO_LABEL_STUDIO_API_TOKEN` -- a Label Studio Personal Access Token
generated once by an admin user in the Label Studio instance itself, and
configured server-side only (never sent to the browser) -- NOT the
requesting WebODM user's own Tapis credential, which is a completely
separate thing used only for the human deep-link login.

Endpoints and payload shapes below were verified against Label Studio's real,
current REST API reference (not guessed from memory):
- Create project:  POST /api/projects/            https://api.labelstud.io/api-reference/api-reference/projects/create
- Bulk task import: POST /api/projects/{id}/import https://api.labelstud.io/api-reference/api-reference/projects/import-tasks
- Create webhook:  POST /api/webhooks/             https://api.labelstud.io/api-reference/api-reference/webhooks/create
- Project deep-link URL pattern (`/projects/{id}/data`): confirmed directly
  against Label Studio's own frontend source, not guessed --
  `web/apps/labelstudio/src/pages/Projects/Projects.jsx` (HumanSignal/label-studio)
  redirects bare `/projects/:id` to `/projects/${id}/data` (the Data Manager tab).

Structure and error-handling style mirror coreplugins/ckan/publisher.py -- the
existing precedent in this repo for a plugin's HTTP client module talking to
an external service server-side -- not its specific API (CKAN vs. Label
Studio are unrelated services).
"""

import logging
from xml.sax.saxutils import quoteattr

import requests
from django.conf import settings

logger = logging.getLogger('app.logger')

# Project create/import/webhook-register are all small, synchronous calls --
# no long-running work happens inside Label Studio for any of them.
DEFAULT_REQUEST_TIMEOUT = 30  # seconds


class LabelStudioConfigError(RuntimeError):
    """Raised when WO_LABEL_STUDIO_URL / WO_LABEL_STUDIO_API_TOKEN aren't configured."""


class LabelStudioAPIError(RuntimeError):
    """Raised when Label Studio's API returns a non-2xx response, or the request
    could not be sent at all (network error). Mirrors the "raise a clear
    exception rather than fail silently" style of coreplugins/ckan/publisher.py.
    """

    def __init__(self, message, status_code=None, response_body=None):
        super().__init__(message)
        self.status_code = status_code
        self.response_body = response_body


# ── Config / low-level request helper ─────────────────────────────────────────

def _base_url():
    url = (getattr(settings, 'WO_LABEL_STUDIO_URL', '') or '').strip()
    if not url:
        raise LabelStudioConfigError(
            "WO_LABEL_STUDIO_URL is not configured -- the embeddings plugin's "
            "Label Studio integration is inactive until it is set."
        )
    return url.rstrip('/')


def _auth_headers():
    token = (getattr(settings, 'WO_LABEL_STUDIO_API_TOKEN', '') or '').strip()
    if not token:
        raise LabelStudioConfigError(
            "WO_LABEL_STUDIO_API_TOKEN is not configured -- see Decision 32 in "
            "docs/design/2026-07-22-geospatial-embeddings-classification.md. "
            "This must be a Label Studio Personal Access Token generated by an "
            "admin inside the Label Studio instance itself -- it is NOT the "
            "requesting user's Tapis JWT."
        )
    return {'Authorization': f'Bearer {token}'}


def _request(method, path, **kwargs):
    """
    Real HTTP call to Label Studio's own REST API (`requests`, not mocked).
    Raises LabelStudioAPIError on any non-2xx response or network failure --
    callers should not have to guess success from a None/False return.
    """
    url = f'{_base_url()}{path}'
    headers = _auth_headers()
    headers.update(kwargs.pop('headers', None) or {})
    timeout = kwargs.pop('timeout', DEFAULT_REQUEST_TIMEOUT)

    try:
        response = requests.request(method, url, headers=headers, timeout=timeout, **kwargs)
    except requests.RequestException as e:
        logger.exception('Label Studio API request failed: %s %s', method, url)
        raise LabelStudioAPIError(f'Could not reach Label Studio at {url}: {e}') from e

    if not response.ok:
        body_snippet = (response.text or '')[:500]
        logger.error(
            'Label Studio API error %s on %s %s: %s',
            response.status_code, method, url, body_snippet,
        )
        raise LabelStudioAPIError(
            f'Label Studio API returned {response.status_code} for {method} {url}: {body_snippet}',
            status_code=response.status_code,
            response_body=body_snippet,
        )

    if not response.content:
        return {}
    try:
        return response.json()
    except ValueError:
        return {}


# ── label_config generation ────────────────────────────────────────────────────

def build_label_config(label_classes, image_data_key='image', choice_mode='single'):
    """
    Build the XML `label_config` string Label Studio's project-create API
    expects, from a PLAIN LIST of label-class dicts -- NOT from a
    `label_classes` DB query. The real `label_classes` table (site-scoped,
    falling back to instance-wide defaults -- design spec "Embeddings DB
    Schema" / Decision 12) lives in `embeddingsdb`, which does not exist yet.
    Until it does, the CALLER is responsible for sourcing this list:
      - today: a hardcoded Phase 1 default 7-class taxonomy (see
        api_views.py's TaskLabelView, clearly commented as a placeholder)
      - later: a real `label_classes` query, once embeddingsdb exists
    This function does not hardcode any taxonomy itself.

    Args:
        label_classes: list of dicts, each with:
            - 'value' (str, required): canonical vocabulary key -- must match
              a real `label_classes.value` once that table exists; this is
              what a `labels` row's `value` should be set to after annotation.
            - 'display_name' (str, optional): human-readable text shown to
              the annotator; falls back to 'value' if omitted.
            - 'color_hex' (str, optional): CSS color (e.g. '#e6194b') Label
              Studio renders as the choice's background swatch.
        image_data_key: the task `data` field name the generated interface
            reads the tile image URL from (interpolated as `$<image_data_key>`
            in the XML). Every task object passed to `import_tasks()` must
            set `data[image_data_key]` to match, or Label Studio's import
            will reject it (task data is validated against label_config).
        choice_mode: the `<Choices>` tag's `choice` attribute -- 'single'
            (default: one label per tile) or 'multiple'.

    Label Studio's `<Choice>` tag only ever shows one attribute (`value`) to
    the annotator, but separately supports an `alias` attribute that -- per
    Label Studio's own docs -- "replaces the choice value in the annotation
    results" when set, and is never shown in the UI. So this generator renders
    `display_name` as `value` (what the human annotator sees) and the
    canonical `value` as `alias` (what actually comes back in the
    ANNOTATION_CREATED/UPDATED webhook payload) -- this is what lets a real
    webhook handler upsert `labels.value` as the true taxonomy key rather than
    whatever human-readable text happened to be on screen.

    Returns a well-formed XML string. Not schema-validated against Label
    Studio itself here (no such endpoint is called) -- see this module's own
    tests for an `xml.etree.ElementTree.fromstring()` well-formedness check.
    """
    if not label_classes:
        raise ValueError('build_label_config() requires at least one label class.')

    choice_tags = []
    for lc in label_classes:
        value = lc.get('value')
        if not value:
            raise ValueError(f"label class {lc!r} is missing required 'value'.")
        display_name = lc.get('display_name') or value
        color_hex = lc.get('color_hex')

        attrs = f'value={quoteattr(str(display_name))} alias={quoteattr(str(value))}'
        if color_hex:
            attrs += f' background={quoteattr(str(color_hex))}'
        choice_tags.append(f'    <Choice {attrs}/>')

    return (
        '<View>\n'
        f'  <Image name="image" value="${image_data_key}"/>\n'
        f'  <Choices name="label" toName="image" choice="{choice_mode}">\n'
        + '\n'.join(choice_tags) + '\n'
        '  </Choices>\n'
        '</View>'
    )


# ── API calls ──────────────────────────────────────────────────────────────────

def create_project(title, label_config):
    """
    POST /api/projects/ -- create a new Label Studio project.

    Design spec, "Label Studio Integration: Full Mechanics" step 1: `title`
    is the task name + timestamp; `label_config` is generated by
    `build_label_config()` above (from whatever label classes the caller
    sourced -- see that function's docstring).

    Returns Label Studio's own response dict, including at least 'id' (the
    new project's integer id, needed by import_tasks()/register_webhook()
    and to build the deep-link URL).
    """
    payload = {'title': title, 'label_config': label_config}
    return _request('POST', '/api/projects/', json=payload)


def import_tasks(project_id, tasks):
    """
    POST /api/projects/{id}/import -- bulk task import (Label Studio's real
    bulk-import endpoint; accepts a JSON array of task objects directly).

    Design spec, "Label Studio Integration: Full Mechanics" step 2: one
    Label Studio task per selected tile. Each task dict must already be
    shaped for Label Studio's own import API:
      - 'data' (dict, required): validated against label_config on import --
        must include the image_data_key used when building label_config
        (default 'image') pointing at a fetchable image URL for that tile.
      - 'meta' (dict, optional but expected in practice): arbitrary JSON --
        this is where OUR OWN join key belongs. Per the design spec, this
        must carry `tile_observation_id` (and `webodm_task_id`) so the
        ANNOTATION_CREATED/UPDATED webhook payload can be matched back to
        the right row -- NOT inferred from image filenames.

    Building the 'data'/'meta' contents is the CALLER's job -- this module
    knows nothing about tiles, WebODM tasks, or tile_observation_ids; it only
    forwards whatever task list it's given to Label Studio's import endpoint.

    Returns Label Studio's own import response (Community edition returns
    task/annotation counts synchronously; other editions return an
    `import_id` for async polling against /api/projects/{id}/imports/{id} --
    not distinguished here, since either shape is just passed through as-is).
    """
    if not tasks:
        raise ValueError('import_tasks() requires at least one task.')
    for i, task in enumerate(tasks):
        if 'data' not in task:
            raise ValueError(f'tasks[{i}] is missing the required "data" field.')
    return _request('POST', f'/api/projects/{project_id}/import', json=tasks)


def register_webhook(project_id, webhook_url, secret):
    """
    POST /api/webhooks/ -- register a webhook scoped to `project_id` (via the
    'project' field, so it fires only for this project's annotations, not
    organization-wide), for ANNOTATION_CREATED/ANNOTATION_UPDATED (Decision
    10). `send_for_all_actions=False` + explicit `actions` ensures only those
    two events are sent, not every supported webhook action.

    `secret` is sent as a custom header (via the webhook's own 'headers'
    field) rather than an HMAC signature -- Label Studio's webhook API has no
    built-in payload-signing mechanism, so a shared-secret header is the real
    mechanism `.../labelstudio-webhook` verifies via `hmac.compare_digest`
    per Decisions 10/29 (that handler is still a stub -- see
    LabelStudioWebhookView in api_views.py -- this call only registers the
    webhook, it doesn't implement the receiving side).
    """
    payload = {
        'url': webhook_url,
        'project': project_id,
        'actions': ['ANNOTATION_CREATED', 'ANNOTATION_UPDATED'],
        'send_payload': True,
        'send_for_all_actions': False,
        'is_active': True,
        'headers': {'X-WebODM-Embeddings-Secret': secret},
    }
    return _request('POST', '/api/webhooks/', json=payload)


def project_url(project_id):
    """
    Deep-link URL to a project's Data Manager page in Label Studio's own UI --
    the real URL its UI uses to open a project (confirmed against Label
    Studio's own frontend source, not guessed -- see module docstring).
    """
    return f'{_base_url()}/projects/{project_id}/data'
